remove invalid call [YT AD-1064]
an unneeded invalid variable setting was crashing the process, causing further processing not to happen

ReferenceError: Cannot access 'cacheChanged' before initialization line #1557